services:
  db:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_USER: odm_user
      POSTGRES_PASSWORD: odm_password
      POSTGRES_DB: odm
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odm_user -d odm"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

volumes:
  postgres-data:
